FROM jnijni/elixir-docker

# Fix mix to stop it from re-downloading hex and rebar
ADD mix_base /.mix

# Start website
EXPOSE 8080
ENV PORT 8080
ENV MIX_ENV dev
WORKDIR /src
CMD yes | mix do clean, deps.get && mix phoenix.start
